@startuml

!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!includeurl SPRITESURL/java.puml
!includeurl SPRITESURL/postgresql.puml

scale 600 width
skinparam {
  nodesep 100
  padding 5
  monochrome true
}

title External Dependencies

actor Client
component "<$java>\nRunService" as RunService
database "<$postgresql>\nPostgreSQL" as PostgreSQL
component ExternalService

Client -r-> RunService: 3.
RunService -d-> PostgreSQL: 1.
RunService -r-> ExternalService: 2.

@enduml