@startuml

!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!includeurl SPRITESURL/java.puml
!includeurl SPRITESURL/postgresql.puml

scale 600 width
skinparam {
  nodesep 100
  padding 5
  monochrome true
}

title External Dependencies

component "<$java>\nRunService" as RunService
database "<$postgresql>\nPostgreSQL" as PostgreSQL
RunService -d-> PostgreSQL

actor Client
component ExternalService

Client -r-> RunService
RunService -r-> ExternalService

@enduml