@startuml

scale 800 width
skinparam {
  padding 5
  monochrome true
  ParticipantPadding 30
}
autoactivate on

title Example of Successful Call

actor Client
participant RunService
participant ExternalService
database Database

Client -> RunService: POST /runs?item_count=2
RunService -> Database: INSERT INTO run
return {id: 1}
RunService -> ExternalService: POST /item
return 200 OK
RunService -> ExternalService: POST /item
return 200 OK
RunService -> Database: UPDATE run SET status = "SUCCESS"
return
return 200 OK: {id: 1, status: SUCCESS}

@enduml