@startuml

scale 800 width
skinparam {
  padding 5
  monochrome true
  ParticipantPadding 30
}
autoactivate on

title Example of Unsuccessful Call

actor Client
participant App
participant ExternalService
database Database

Client -> App: POST /runs?item_count=3
App -> Database: INSERT INTO run
return {id: 1}
App -> ExternalService: POST /item
return 200 OK
App -> ExternalService: POST /item
return 503 SERVICE UNAVAILABLE
App -> Database: UPDATE run SET status = "FAILED"
return
return 200 OK: {id: 1, status: FAILED}

@enduml